apiVersion: v1
kind: Service
metadata:
  name: titanic-dataprep-service
spec:
  type: NodePort
  selector:
    app: titanic-dataprep
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007  # Exposes the service at this port
