apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-model-deployment
spec:
  replicas: 2  # Runs two instances of your model
  selector:
    matchLabels:
      app: titanic-model
  template:
    metadata:
      labels:
        app: titanic-model
    spec:
      containers:
      - name: model-container
        image: data_model:latest  # This should match your Docker image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: titanic-model-service
spec:
  type: NodePort
  selector:
    app: titanic-model
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30007  # Exposes the service at this port
