FROM python:3.10-slim

WORKDIR /usr/src/app

COPY . /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "./EGT309_Data_Modelling_Code.py"]