apiVersion: v1
kind: Service
metadata:
  name: eda-service
  namespace: aidp
spec:
  type: LoadBalancer
  selector:
    app: eda
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
