apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-deployment
  namespace: aidp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eda
  template:
    metadata:
      labels:
        app: eda
    spec:
      containers:
      - name: eda
        image: triedlotsofnames/eda-container:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-storage
          mountPath: /Data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-pvc
