apiVersion: batch/v1
kind: Job
metadata:
  name: preprocess-job
  namespace: aidp
spec:
  template:
    spec:
      containers:
      - name: preprocess
        image: triedlotsofnames/preprocess-container:latest
        volumeMounts:
        - name: data-storage
          mountPath: /Data
      restartPolicy: Never
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-pvc
